"""Deliverable 7 -- input drift detection.

Compares the TRAINING distribution against the 100-row generated dataset used
for prediction in Deliverable 5.

  * numeric columns   -> two-sample Kolmogorov-Smirnov test
  * categorical cols  -> Chi-square test on category frequencies
  * every column      -> Population Stability Index (industry standard)

    python src/drift.py
"""
import argparse, json, os, sys
import numpy as np, pandas as pd
from scipy import stats

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from preprocess import CATEGORICAL, FEATURES, NUMERIC, clean, load_raw  # noqa: E402

ALPHA = 0.05


def psi(ref: np.ndarray, cur: np.ndarray, bins: int = 10) -> float:
    """Population Stability Index. <0.1 stable, 0.1-0.25 moderate, >0.25 major."""
    edges = np.unique(np.quantile(ref, np.linspace(0, 1, bins + 1)))
    if len(edges) < 3:
        edges = np.linspace(min(ref.min(), cur.min()),
                            max(ref.max(), cur.max()), bins + 1)
    edges[0], edges[-1] = -np.inf, np.inf
    r = np.histogram(ref, edges)[0] / len(ref)
    c = np.histogram(cur, edges)[0] / len(cur)
    eps = 1e-6
    r, c = np.clip(r, eps, None), np.clip(c, eps, None)
    return float(np.sum((c - r) * np.log(c / r)))


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--reference", default="artifacts/train_reference.csv",
                    help="falls back to the raw training csv")
    ap.add_argument("--current", default="data/random_100.csv")
    ap.add_argument("--raw", default="data/data.csv")
    ap.add_argument("--out", default="artifacts")
    args = ap.parse_args()
    os.makedirs(args.out, exist_ok=True)

    ref = (pd.read_csv(args.reference) if os.path.exists(args.reference)
           else clean(load_raw(args.raw)))
    cur = pd.read_csv(args.current)
    ref, cur = ref[FEATURES], cur[FEATURES]

    rows = []
    for col in FEATURES:
        r, c = ref[col].to_numpy(float), cur[col].to_numpy(float)
        p_index = psi(r, c)
        if col in NUMERIC:
            test, stat, p = "KS", *stats.ks_2samp(r, c)
        else:
            cats = sorted(set(ref[col]) | set(cur[col]))
            obs = np.array([[(ref[col] == k).sum() for k in cats],
                            [(cur[col] == k).sum() for k in cats]], float)
            obs = obs[:, obs.sum(axis=0) > 0]
            # scale reference counts to the current sample size so the chi-square
            # tests the *shape* of the distribution, not the sample sizes.
            obs[0] = obs[0] * obs[1].sum() / obs[0].sum()
            test = "Chi2"
            stat, p = stats.chisquare(f_obs=obs[1], f_exp=np.clip(obs[0], 1e-6, None))[:2]
        drifted = bool(p < ALPHA)
        rows.append({"feature": col, "type": "numeric" if col in NUMERIC else "categorical",
                     "test": test, "statistic": round(float(stat), 4),
                     "p_value": float(p), "psi": round(p_index, 4),
                     "psi_severity": ("none" if p_index < 0.1 else
                                      "moderate" if p_index < 0.25 else "major"),
                     "drift_detected": drifted,
                     "ref_mean": round(float(np.mean(r)), 3),
                     "cur_mean": round(float(np.mean(c)), 3)})

    res = pd.DataFrame(rows).sort_values("psi", ascending=False)
    n_drift = int(res.drift_detected.sum())
    share = n_drift / len(res)
    verdict = ("SIGNIFICANT INPUT DRIFT" if share >= 0.5 else
               "PARTIAL DRIFT" if n_drift else "NO DRIFT")

    md = ["# Deliverable 7 - Input Drift Detection", "",
          f"Reference: training data (`{len(ref)}` rows) | "
          f"Current: generated prediction data (`{len(cur)}` rows)",
          f"Significance level alpha = {ALPHA}", "",
          res.to_markdown(index=False, floatfmt=".4f"), "",
          f"- Features flagged as drifted: **{n_drift}/{len(res)}** ({share:.0%})",
          f"- **Overall verdict: {verdict}**", "",
          "PSI reading: `<0.10` stable, `0.10-0.25` moderate shift, "
          "`>0.25` major shift.", "",
          "**Interpretation.** The prediction set was generated by sampling each "
          "feature uniformly across its observed range rather than from the joint "
          "training distribution, so the marginal distributions are flatter and "
          "the feature correlations present in real patients are absent. A model "
          "monitored in production should raise an alert here and the predictions "
          "on this batch should be treated as low-confidence until the incoming "
          "data source is investigated."]
    out = "\n".join(md)
    open(f"{args.out}/drift_report.md", "w").write(out)
    res.to_csv(f"{args.out}/drift_report.csv", index=False)
    json.dump({"verdict": verdict, "n_drifted": n_drift,
               "features": res.to_dict("records")},
              open(f"{args.out}/drift.json", "w"), indent=2)
    print(out)


if __name__ == "__main__":
    main()
